remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [This is asatinmarch]
author: [asatinmarch]
description: [Record the learning process]

paginate: 5 # amount of posts to show
paginate_path: /page:num/
